import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import axios from "axios";
import MovieRenderer from "@/components/MovieRenderer";

export default function Home() {
  const [query, setQuery] = useState("");
  const [foundMovies, setFoundMovies] = useState([]);
  const api_key = "d19ebd834974f0ff6ca640f7aee3a7cc";
  const genre_response_query = `https://api.themoviedb.org/3/genre/movie/list?api_key=${api_key}`;
  const handleGenreSearch = async () => {
    // Figure out which genre the user selected
    // uses axios to get the list of genres
    const genreResponse = await axios.get(genre_response_query);

    // Find the genre that matches the query
    const selectedGenre = genreResponse.data.genres.find(
      (g) => g.name.toUpperCase() === query.toUpperCase()
    );

    // If the genre doesn't exist, set movies to an empty array and return
    if (!selectedGenre) {
      setMovies([]);
      return;
    }
    // If the genre does exist, use axios to get the movies
    const response = await axios.get(
      `https://api.themoviedb.org/3/discover/movie?api_key=${api_key}&sort_by=popularity.desc&with_genres=${selectedGenre.id}`
    );

    // Set the movies state to the results of the API call

    setFoundMovies(response.data.results);
  };

  const handleQueryEnter = (event) => {
    if (event.key === "Enter") {
      handleGenreSearch();
    }
  };

  return (
    <>
      <Head>
        <title>Movie Content Group Search Prototype</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container body-connect">
        <nav className="nav_shadow">
          <ul>
            <li>
              <strong>Movie Content Group Search</strong>
            </li>
          </ul>
        </nav>
        <br />
        <br />
        <h1 className="text-center">Movie Content Group Search Prototype</h1>
        <h3 className="text-center">Team Miracle Workers</h3>
        <input
          type="text"
          placeholder="Search for genre"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          onKeyDown={handleQueryEnter}
        />
        <button onClick={handleGenreSearch} onKeyDown={handleQueryEnter}>
          Search
        </button>
        <MovieRenderer movies={foundMovies} />
      </main>
    </>
  );
}
